version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: mysql_database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: mysql
      MYSQL_USER: Irina
      MYSQL_PASSWORD: :.%L9pJPd=%C555l_w9#YpTEPcS97m7+
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
